name: Testnet Faucet

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  testnet:
    runs-on: ubuntu-latest
    environment: testnet
    env:
      TESTNET_ADDRESS: ${{ secrets.TESTNET_ADDRESS }}
      CHAINSTACK_API_KEY: ${{ secrets.CHAINSTACK_API_KEY }}
      INFURA_KEY: ${{ secrets.INFURA_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --group dev

      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 135

      - name: Run faucet script
        run: uv run python scripts/drip.py
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
